######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 15 15:35:22 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/mqttalkapp.hpp src/mqttclient.hpp
SOURCES += src/main.cpp src/mqttalkapp.cpp src/mqttclient.cpp
LIBS += -lmosquittopp
